const mongoose=require("mongoose")
const pdfHistoryDataSchema=mongoose.Schema({
    fileName:{
        type:String
    },
    creationDate:{
        type:Date,
        default:new Date()
    },
    userEmail:{
        type:String
    },
    FoodItems:[{
        foodlist:{
            type:Array,
            default:[]
        },
        disease:{
            type:String,
            default:""
        }
    }],
    vitalsList:[
        {
            lower_limit:{
                type:Number,
                default:0
            },
            result:{
                type:Number,
                default:0
            },
            unit:{
                type:String,
                default:""
            },
            upper_limit:{
                type:Number,
                default:0
            },
            testName:{
                type:String,
                default:""
            },
            vitalName:{
                type:String,
            }
        }
    ]
})
const pdfHistoryDataModel=mongoose.model("pdfHistoryDataModel",pdfHistoryDataSchema)
module.exports=pdfHistoryDataModel